name: manage-azure-policy-84cec9a6
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'odl/policies/Resource_Groups_append_CreatedOnDate_Tag_f7ca10eb-4686-4317-966c-db1a80c1b1f4/**'
#      - .github/workflows/manage-azure-policy-84cec9a6.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_84cec9a6}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          odl/policies/Resource_Groups_append_CreatedOnDate_Tag_f7ca10eb-4686-4317-966c-db1a80c1b1f4/**
